---
title: "Writing a great story for data science projects - Spring 2026 "
subtitle: "This is a Report Template Quarto"
author: "Sabna Pillai (Advisor: Dr. Cohen)"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: Capstone Projects in Data Science
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

Slides: [slides.html](slides.html){target="_blank"} ( Go to `slides.qmd`
to edit)

::: callout-important
**Remember:** Your goal is to make your audience understand and care
about your findings. By crafting a compelling story, you can effectively
communicate the value of your data science project.

Carefully read this template since it has instructions and tips to
writing!

Nice report!
:::

## Introduction

## we are still in the planning phase:

#1. Whether to do comparitive analysis using just 2 cnn architectures or include more.

#2. To analysis various knee pathologies like :ACL tear, knee ostheritstics, meniscus tears or just to analysis the acl tear.


The aim of this study is to conduct a comparative analysis of the performance of few DL techniques, like Res-Net and Dense Net. As a result of exploring the capabilities of these two neural networks, we are aiming to determine their effectiveness and suitability for classifying the knee pathologies. Deep Learning (DL) architectures, specifically Convolutional Neural Networks (CNNs), are a flexible class of computational models that combine the strengths of hierarchical feature extraction and automated pattern recognition (LeCun et al. 2015). Like traditional image processing, CNNs can model complex visual data, such as medical radiographs and scans. However, modern architectures like DenseNet (Densely Connected Networks) and ResNet (Residual Networks) extend standard CNNs by incorporating advanced connectivity patterns such as skip connections and feature concatenation which account for the vanishing gradient problem and the need for efficient feature reuse.[@wang2024deep] noted that manual diagnosis of anterior cruciate ligament (ACL) tears often struggles with inter-observer variability and the high cognitive load placed on radiologists. This made it difficult to provide consistent, rapid outcomes for patients. But the specialized layers in ResNet and DenseNet help model the complex relationships within image patches and allow for the detection of patterns that are not captured by traditional linear measurements.
Similarly,  [@javed2021efficient] utilize a deep learning approach to investigate the efficient detection of knee ACL injuries from MRI data. In their analysis, they demonstrate how optimized CNN architectures account for variation in regional joint data, proving that deep learning provides both the flexibility and tractability required for reliable medical classification.
This study investigates the potential for diagnosis of knee pathologies particularly focusing on the accurate classification of ACL injuries. To analyze these risks, we will apply  different cnn models which can be used for complex data.  


## Literature review:

1.	Awan, M. J., Rahim, M. S. M., Salim, N., Mohammed, M. A., Garcia-Zapirain, B., & Abdulkareem, K. H. (2021). Efficient detection of knee anterior cruciate ligament from magnetic resonance imaging using deep learning approach. Diagnostics, 11(1), 105. https://doi.org/10.3390/diagnostics11010105

This study presents an automated deep learning system to detect anterior cruciate ligament (ACL) injuries from magnetic resonance imaging (MRI) scans of the knee. ACL injuries are common in athletes, particularly in sports like football, basketball, and soccer. The goal of the research was to create an efficient method to detect ACL injuries at an early stage without the need for radiologists, using a customized 14-layer ResNet-14 convolutional neural network (CNN) architecture. The performance of the ResNet-14 model was evaluated using metrics such as accuracy, sensitivity, specificity, precision, and F1 score, with results of 92.0%, 91.6%, 94.6%, 91.6%, and 92.3%, respectively. The model achieved exceptional Area Under the Curve (AUC) values for each class of ACL injury: 0.980 for healthy, 0.970 for partial tear, and 0.999 for fully ruptured tear. The results indicate that this model is highly effective in detecting and classifying ACL injuries, distinguishing between healthy knees, partial tears, and fully ruptured ACLs. The system provides an automated and accurate alternative to manual evaluation by radiologists, making it a promising tool for early ACL injury diagnosis in athletes.


2.	Wang, X., Wu, Y., Li, J., Li, Y., & Xu, S. (2024). Deep learning-assisted automatic diagnosis of anterior cruciate ligament tear in knee magnetic resonance images. Tomography, 10(8), 1263-1276. https://doi.org/10.3390/tomography10080094

This study focuses on developing a deep learning model for the automatic detection of anterior cruciate ligament (ACL) tears from knee magnetic resonance imaging (MRI) scans.  The model was tested on a publicly available MRNet dataset that includes 1,250 knee MRI exams across three distinct views: axial, coronal, and sagittal. The experimental results showed that SGNET outperforms other models in ACL tear detection, achieving: Accuracy: 92.50%, Sensitivity: 92.59%, Specificity: 92.42%, AUC (Area Under Curve): 0.9747. The study highlights the potential of SGNET as a reliable diagnostic tool for detecting ACL injuries. The model's ability to accurately identify ACL tears could reduce the misdiagnosis rate and support clinicians in streamlining the diagnostic process, improving the overall efficiency and accuracy of ACL injury assessments.

## Methods

-   Detail the models or algorithms used.

-   Justify your choices based on the problem and data.

*The common non-parametric regression model is*
$Y_i = m(X_i) + \varepsilon_i$*, where* $Y_i$ *can be defined as the sum
of the regression function value* $m(x)$ *for* $X_i$*. Here* $m(x)$ *is
unknown and* $\varepsilon_i$ *some errors. With the help of this
definition, we can create the estimation for local averaging i.e.*
$m(x)$ *can be estimated with the product of* $Y_i$ *average and* $X_i$
*is near to* $x$*. In other words, this means that we are discovering
the line through the data points with the help of surrounding data
points. The estimation formula is printed below [@R-base]:*

$$
M_n(x) = \sum_{i=1}^{n} W_n (X_i) Y_i  \tag{1}
$$$W_n(x)$ *is the sum of weights that belongs to all real numbers.
Weights are positive numbers and small if* $X_i$ *is far from* $x$*.*

*Another equation:*

$$
y_i = \beta_0 + \beta_1 X_1 +\varepsilon_i
$$

## Analysis and Results

### Data Exploration and Visualization

-   Describe your data sources and collection process.

-   Present initial findings and insights through visualizations.

-   Highlight unexpected patterns or anomalies.



### Modeling and Results

-   Explain your data preprocessing and cleaning steps.

-   Present your key findings in a clear and concise manner.

-   Use visuals to support your claims.

-   **Tell a story about what the data reveals.**

```{r}

```

### Conclusion

-   Summarize your key findings.

-   Discuss the implications of your results.

## References
